config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  post "/collections/:id/issues/new", to: "collection_issues#create"

  resources :issues do
    collection do
      get 'export_csv'
    end
  end
  
  get "collections/:id/export_csv", to: "collection_issues#export_csv"

  resources :collections, except: :show do
    resources :issues, controller: "collection_issues"
  end

  # resources :collection_issues
  resources :issues
  # resources :collection_issues

  # get "/collections/:id/issues", to: "collection_issues#index"
  # get "/collections/:id/new", to: "collection_issues#new"
  # post "/collections/:id/new", to: "collection_issues#new"
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/collection.rb
class Collection < ApplicationRecord
  has_many :issues
end

app/models/feature.rb
class Feature < ApplicationRecord
  has_many :issue_features
  has_many :issues, through: :issue_features
end

app/models/issue.rb
require 'csv'
class Issue < ApplicationRecord
  has_many :issue_features
  has_many :features, through: :issue_features
  belongs_to :collection

  enum status: {
    do_not_have: 0,
    ordered: 1,
    have: 2
  }

  def incomplete?
    title == nil
  end

  def missing
    where(status: ["do_not_have", nil])
  end

  def ebay_search
    formatted_title = title.parameterize(separator: '+')
    "https://www.ebay.com/sch/i.html?_from=R40&_nkw=#{formatted_title}&_sacat=0"
  end

  def self.to_csv
    attributes = %w{id title}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      Issue.all.each do |issue|
        csv << attributes.map{ |attr| issue.send(attr) }
      end
    end
  end
end

app/models/issue_feature.rb
class IssueFeature < ApplicationRecord
  belongs_to :issue
  belongs_to :feature
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/collection_issues_controller.rb
class CollectionIssuesController < ApplicationController
  def index
    @collection = Collection.find(params[:collection_id])
    @issues = @collection.issues
  end

  def edit
    # binding.pry
    @collection = Collection.find(params[:collection_id])
    @issue = Issue.find(params[:id])
  end

  def new
  end

  def create
    # binding.pry
    @collection = Collection.find(params[:id])

    issue = @collection.issues.new(issue_params)
    if issue.save
      redirect_to collection_issues_path(@collection)
    end
  end

  def update
    @collection = Collection.find(params[:collection_id])
    @issue = Issue.find(params[:id])
    if @issue.update(issue_params)
      redirect_to collection_issues_path(@collection)
    end
  end

  def export_csv
    @collection = Collection.find(params[:collection_id])
    @issues = @collection.all

    respond_to do |format|
      format.csv { send_data @issues.to_csv, filename: "#{@collection.name}_issues_#{Date.today}.csv" }
    end

    redirect_to collection_issues_path(@collection)
  end

  private
  def issue_params
    params.require(:issue).permit(:collection_id, :collector_id, :condition, :date, :origin, :status, :price, :title)
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def index
    @issues = Issue.all
  end

  def show
    @issue = Issue.find(params[:id])
  end

  def new
    @issue = Issue.new
  end

  def create
    @issue = Issue.new(issue_params)
    if @issue.save
      redirect_to @issue
    else
      render 'new'
    end
  end

  def export_csv
    @issues = Issue.all

    respond_to do |format|
      format.csv { send_data @issues.to_csv, filename: "issues_#{Date.today}.csv" }
    end

    # redirect_to collection_issues_path(@collection)
  end

  private

  def issue_params
    params.require(:issue).permit(:collection_id, :condition, :date, :origin, :status, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/collection_issues/_form.html.erb
  <%= form_with model: @issue, method: method, url: url, class: 'issue_form', data: {turbo: false} do |f| %>  
    <%= f.label :collector_id, 'ID: (serial number, issue number, etc):' %><br>
    <%=  f.text_field :collector_id %><br>
    <%= f.label :title, 'Title/Name of Item:' %><br>
    <%=  f.text_field :title %><br>
    <%= f.label :date, 'Date produced:' %><br>
    <%=  f.text_field :date %><br>
    <%= f.label :price, 'Price at Purchase:' %><br>
    <%=  f.text_field :price %><br>
    <%= f.label :status, 'Ordered, Owned, Not Owned:' %><br>
    <%=  f.text_field :status %><br>
    <%= f.label :origin, 'Where this item was purchased:' %><br>
    <%=  f.text_field :origin %><br>
    <%= f.label :condition, 'Condition:' %><br>
    <%=  f.text_field :condition %><br>
    <%= f.submit %>
  <% end %>

app/views/collection_issues/edit.html.erb
<h1>Update <%= @issue.id %></h1>

  <%= render partial: 'form', locals: { method: :patch, url: collection_issue_path(@collection, @issue), class: 'issue_form'} %>

app/views/collection_issues/index.html.erb
<body>
  <div class="row">
    <h3 class='col-12'><%= @collection.name %></h3>
  </div>

  <%= link_to "Export as CSV", export_csv_issues_path(format: :csv), class: "btn btn-primary" %>

  <p><%= link_to "Add an Issue", new_collection_issue_path(@collection.id) %></p>

  <table class="table">
    <thead>
      <tr class="tr">
        <th class="th1">Collector's ID</th>
        <th class="th1">Title</th>

        <% if @issues.where(condition: nil) == [] %>
          <th class="th1">Condition</th>
        <% end %>

        <% if @issues.where(date: nil) == [] %>
          <th class="th1">Date</th>
        <% end %>

        <% if @issues.where(origin: nil) == [] %>
          <th class="th1">Origin</th>
        <% end %>

        <th class="th1">Status</th>
      </tr>
    </thead>

    <tbody>
      <% @issues.each do |issue| %>
        <tr class="tr">
          <% if !issue.incomplete? %>
            <td style="text-align:center"><%= issue.collector_id %></td>
            <td style="text-align:center"><%= issue.title %></td>
            <td style="text-align:center"><%= link_to "Update Item", edit_collection_issue_path(@collection, issue) %></td>

            <% if @issues.where(condition: nil) == [] %>
              <td style="text-align:center"><%= issue.condition %></td>
            <% end %>

            <% if @issues.where(date: nil) == [] %>
            <td style="text-align:center"><%= issue.date %></td>
            <% end %>

            <% if @issues.where(origin: nil) == [] %>
            <td style="text-align:center"><%= issue.origin %></td>
            <% end %>

            <% if @issues.where(price: nil) == [] %>
            <td style="text-align:center"><%= issue.price %></td>
            <% end %>

            <% if issue.status == "do_not_have" %>
              <td style="text-align:center"><%= link_to "Find this item", issue.ebay_search %></td>
            <% elsif issue.status == "have" %>
              <td style="text-align:center">owned</td>
            <% elsif issue.status == "ordered" %>
              <td style="text-align:center">ordered</td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</body>

app/views/collection_issues/new.html.erb
<%= render partial: 'form', locals: { method: :post, url: new_collection_issue_path(params[:collection_id]), class: 'issue_form', local: true}%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CollectorsFriend</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>